
## BASE URL http://bb7fee11.ngrok.io

# Get me the list a valid alert types
GET http://bb7fee11.ngrok.io/api/enums

###
# Get list of registered users
GET http://bb7fee11.ngrok.io/api/user
Content-Type: application/json

###
# Create user
POST http://bb7fee11.ngrok.io/api/user
Content-Type: application/json

{
    "user" : {
		"fullName": "Tester",
		"phoneNumber": "08010000004",
		"gender": "male",
		"address": "Some address",
        "userType": "citizen"
	}
}

###
# Login user
POST http://bb7fee11.ngrok.io/api/user/login
Content-Type: application/json

{
    "phoneNumber" : "09010001001"
}


###

POST  http://bb7fee11.ngrok.io/api/alert
Content-Type: application/json

{
	"alert":{
		"userId":"5eb3db3223a42d001d02b2c9",
		"alertType":"crime",
		"location":"6.4623144,3.4778092",
		"priority": "medium",
		"comment": "testing2",
		"pictures": ["picture1.png", "picture2.png"],
		"videos": ["video1.png", "video2.png"]
	}
}

###
# Get lsit of alerts via user ID
GET http://bb7fee11.ngrok.io/api/alerts/5eb3db3223a42d001d02b2c9
Content-Type: application/json
